name: CI/CD test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Sripragna$1
          MYSQL_DATABASE: 'godatabase'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Create .env File
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ inputs.AWS_ACCESS_KEY_ID }}" > .env
        echo "AWS_SECRET_ACCESS_KEY=${{ inputs.AWS_SECRET_ACCESS_KEY }}" >> .env
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.2

    - name: Wait for MySQL to be ready
      run: |
        until nc -z -v -w30 localhost 3306
        do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    - name: Install project dependencies
      run: |
        go get -d -v ./...
        go build -v

    - name: Run Integration tests
      run: |
        go test ./...
