name: Packer Format and Validate

on:
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true

jobs:
  packer_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env File
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ inputs.AWS_ACCESS_KEY_ID }}" > .env
        echo "AWS_SECRET_ACCESS_KEY=${{ inputs.AWS_SECRET_ACCESS_KEY }}" >> .env
      shell: bash

    - name: Install Packer
      run: |
        curl -fsSL https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip -o packer.zip
        unzip packer.zip
        sudo mv packer /usr/local/bin/
        packer --version
      if: success()

    - name: List Files
      run: ls

    - name: Initialize Packer
      run: packer init aws-debian.pkr.hcl

    - name: Format Packer Template
      run: packer fmt --check aws-debian.pkr.hcl
      continue-on-error: false

    - name: Validate Packer Template
      run: packer validate aws-debian.pkr.hcl

    - name: Build Packer image
      run: packer build aws-debian.pkr.hcl
